version: '3.7'
services:
  antidote1:
    image: itoumlilt/antidotedb:alpine-iptables
    ports:
     - "8087:8087"
    environment:
      NODE_NAME: "antidote@antidote1"
      SHORT_NAME: "true"
    networks:
    - antidote

  antidote2:
    image: itoumlilt/antidotedb:alpine-iptables
    ports:
     - "8088:8087"
    environment:
      NODE_NAME: "antidote@antidote2"
      SHORT_NAME: "true"
    networks:
    - antidote
      
  antidote3:
    image: itoumlilt/antidotedb:alpine-iptables
    ports:
     - "8089:8087"
    environment:
      NODE_NAME: "antidote@antidote3"
      SHORT_NAME: "true"
    networks:
    - antidote

  link:
    image: erlang:21
    command: 'sh -c "echo \"#!/usr/bin/env escript\\n%%! -smp enable -sname erlshell -setcookie antidote\\nmain(_Args) ->\\n  rpc:call(antidote@antidote1, inter_dc_manager, start_bg_processes, [stable]),\\n  rpc:call(antidote@antidote2, inter_dc_manager, start_bg_processes, [stable]),\\n  rpc:call(antidote@antidote3, inter_dc_manager, start_bg_processes, [stable]),\\n  {ok, Desc1} = rpc:call(antidote@antidote1, inter_dc_manager, get_descriptor, []),\\n  {ok, Desc2} = rpc:call(antidote@antidote2, inter_dc_manager, get_descriptor, []),\\n  {ok, Desc3} = rpc:call(antidote@antidote3, inter_dc_manager, get_descriptor, []),\\n  Descriptors = [Desc1, Desc2, Desc3],\\n  rpc:call(antidote@antidote1, inter_dc_manager, observe_dcs_sync, [Descriptors]),\\n  rpc:call(antidote@antidote2, inter_dc_manager, observe_dcs_sync, [Descriptors]),\\n  rpc:call(antidote@antidote3, inter_dc_manager, observe_dcs_sync, [Descriptors]),\\n  io:format(\\\"Connection setup!\\\").\\n\" >/tmp/connect.erl && while ! escript /tmp/connect.erl; do sleep 1; done"'
    networks:
    - antidote

networks:
  antidote:
    driver: bridge